import { NextPage } from "next";
import Head from "next/head";

import UserCreate from "@/components/pages/Create";

const UsersCreate: NextPage = () => {
  return (
    <>
      <Head>
        <title>TMP - Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserCreate />
    </>
  );
};

export default UsersCreate;
