import type { NextPage } from "next";
import Head from "next/head";

import Add from "@/components/pages/Packings/Add";

const AddPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>TMP - Add Packing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Add />
    </>
  );
};

export default AddPage;
