import type { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";

const DyanmicMain = dynamic(() => import("@/components/Main"), {
  suspense: true,
  ssr: false,
});

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>TMP - Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DyanmicMain />
    </>
  );
};

export default Home;
